version: "3.8"
services:
  flask:
    build:
      context: ./src
      dockerfile: Dockerfile.flask
    ports:
      - "3001:3001"
    working_dir: /app
    tty: true

  frontend:
    build:
      context: ./frontend/trading-dashboard
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    working_dir: /app
    tty: true